[package]
name = "creatus-cnfts"
version = "0.0.0"
authors = []

[addresses]
deploy_addr = "_"

[dev-addresses]
deploy_addr = "0x5555"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-token-objects"
